title = "Grim Company"
baseURL = "https://grimcompany.com"
languageCode = "en-us"
theme = "ananke"

SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "G-MLYZ7SLFLX"
enableRobotsTXT = true



[params]
  body_classes = "calisto bg-near-white"
  post_content_classes = "calisto bg-near-white"
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = ""
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3
  mainSections = ["logs", "jointOperations"]

# [services.disqus]
#   shortname = 'grimcompany'